### ISSUE TITLE
数据库同步不可用

### ISSUE THREAD

**Issue by qianketian** [zyw/sqladvisor-web#1]
python manage.py db upgrade

sqlalchemy.exc.ProgrammingError: (_mysql_exceptions.ProgrammingError) (1146, "Table 'sqladvisor.analysis' doesn't exist") [SQL: u'ALTER TABLE analysis MODIFY dbinfo_id INTEGER(11) NULL']

**Comment by zyw** [comment]
在创建数据库之前，创建数据库
python manage.py shell
>>> from manage import db
>>> db.create_all()

**Comment by zyw** [comment]
在创建数据库之前，创建数据库
```
python manage.py shell
from manage import db
db.create_all()
```
