### ISSUE TITLE
为什么删除要用db.session.add方法呢？我是菜鸟，刚学flask，自己新写一个页面，只能用db.session.delete才能进行删除

### ISSUE THREAD

**Issue by gaoquan6297** [zyw/sqladvisor-web#2]
@main.route("/settings/<settings_id>/del", methods=['GET'])
def settings_del(settings_id):
    databaseInfo = DatabaseInfo.query.get(settings_id)
    databaseInfo.status = 0

    db.session.add(databaseInfo)
    db.session.commit()

    return jsonify({'code': 10003, 'success': True, 'message': 'deleted success! '})

**Comment by zyw** [comment]
呵呵！跟你差不多，写这个我也是一边查文档一边写的，我的主业是java
