### ISSUE TITLE
命令行不会报错，web界面报错了

### ISSUE THREAD

**Issue by hotsmile** [zyw/sqladvisor-web#3]
2017-05-13 15:17:32 16009 [Note] 第1步: 对SQL解析优化之后得到的SQL:select had some error 

2017-05-13 15:17:32 16009 [Note] 第2步: SQLAdvisor结束! 

求解惑！！！！！

**Comment by zyw** [comment]
你的操作系统是什么？有没有在命令行试过？

**Comment by hotsmile** [comment]
cenos7 在命令行可以正确执行呀

**Comment by zyw** [comment]
你是使用的自己编译的命令行，还是web系统里面那个，如果是自己编译的，不妨把自己编译的那个，替换掉web里面自带的那个。

**Comment by zyw** [comment]
如果还是不行就在代码里打印一下，看是否正确。

**Comment by hotsmile** [comment]
使用sqladvisor 命令行可以正常，用sqlweb就报错了，在群里面有截图了

**Comment by lanyejingyu** [comment]
加不了qq群，请问是怎么解决的？

**Comment by donhui** [comment]
这个怎么解决的呢，遇到类似问题 @zyw
